-- CreateTable
CREATE TABLE "FinancialData" (
    "year" INTEGER NOT NULL,
    "revenue" DOUBLE PRECISION NOT NULL,
    "costContracting" DOUBLE PRECISION NOT NULL,
    "overhead" DOUBLE PRECISION NOT NULL,
    "salariesAndBenefits" DOUBLE PRECISION NOT NULL,
    "rentAndOverhead" DOUBLE PRECISION NOT NULL,
    "depreciationAndAmortization" DOUBLE PRECISION NOT NULL,
    "interest" DOUBLE PRECISION NOT NULL,
    "interestIncome" DOUBLE PRECISION NOT NULL,
    "interestExpense" DOUBLE PRECISION NOT NULL,
    "gainOnDisposalAssets" DOUBLE PRECISION NOT NULL,
    "otherIncome" DOUBLE PRECISION NOT NULL,
    "incomeTaxes" DOUBLE PRECISION NOT NULL,
    "cashAndEquivalents" DOUBLE PRECISION NOT NULL,
    "accountsReveivable" DOUBLE PRECISION NOT NULL,
    "inventory" DOUBLE PRECISION NOT NULL,
    "propertyPlantAndEquipment" DOUBLE PRECISION NOT NULL,
    "investment" DOUBLE PRECISION NOT NULL,
    "accountsPayable" DOUBLE PRECISION NOT NULL,
    "currentDebtService" DOUBLE PRECISION NOT NULL,
    "taxesPayable" DOUBLE PRECISION NOT NULL,
    "longTermDebtService" DOUBLE PRECISION NOT NULL,
    "loansPayable" DOUBLE PRECISION NOT NULL,
    "equityCapital" DOUBLE PRECISION NOT NULL,
    "retainedEarnings" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "FinancialData_pkey" PRIMARY KEY ("year")
);
